name: "Node: Publish @serverless/sdk-schema"

on:
  push:
    tags:
      - "@serverless/sdk-schema@[0-9]+.[0-9]+.[0-9]+"

jobs:
  publishNewSdkSchemaVersion:
    name: Publish new version
    runs-on: ubuntu-latest
    env:
      # It'll work with secrets.GITHUB_TOKEN (which is provided by GitHub unconditionally)
      # Still then release author would be "github-actions". It's better if it's dedicated repo bot
      GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Buf Setup
        uses: bufbuild/buf-setup-action@v1
      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: |
          cd ./node
          npm install
          cd packages/sdk-schema
          npm install
      - name: Build Protobufs
        working-directory: ./proto
        run: |
          buf build
          buf generate
      - name: Build
        run: npm run build
        working-directory: ./node/packages/sdk-schema
      - name: Publish New Version
        working-directory: ./node/packages/sdk-schema
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
