# PR's only

name: Validate

on:
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: 1

jobs:
  linuxNode16:
    name: '[Linux] Node.js v16: Lint, Formatting, & Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # For commitlint purpose ensure to have complete list of PR commits
          # It's loose and imperfect assumption that PR has no more than 30 commits
          fetch-depth: 30

      - name: Retrieve last main commit (for `git diff` purposes)
        run: |
          git checkout -b pr
          git fetch --prune --depth=30 origin +refs/heads/main:refs/remotes/origin/main
          git checkout main
          git checkout pr

      - name: Retrieve ~/.npm from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**package*.json') }}
          restore-keys: |
            npm-v16-${{ runner.os }}-${{ github.ref }}-
            npm-v16-${{ runner.os }}-refs/heads/main-

      - name: Retrieve node_modules from cache
        id: cacheNodeModules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('package.json') }}
          restore-keys: |
            node-modules-v16-${{ runner.os }}-${{ github.ref }}-
            node-modules-v16-${{ runner.os }}-refs/heads/main-
      - name: Retrieve packages/aws-lambda-otel-extension/node_modules from cache
        id: cacheAwsLambdaOtelExtensionNodeModules
        uses: actions/cache@v2
        with:
          path: packages/aws-lambda-otel-extension/node_modules
          key: packages/aws-lambda-otel-extension/node-modules-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('packages/aws-lambda-otel-extension/package.json') }}
          restore-keys: |
            packages/aws-lambda-otel-extension/node-modules-v16-${{ runner.os }}-${{ github.ref }}-
            packages/aws-lambda-otel-extension/node-modules-v16-${{ runner.os }}-refs/heads/main-
      - name: Retrieve packages/aws-lambda-otel-extension/opt/otel-extension/node_modules from cache
        id: cacheAwsLambdaOtelExtensionOptOtelExtensionNodeModules
        uses: actions/cache@v2
        with:
          path: packages/aws-lambda-otel-extension/opt/otel-extension/node_modules
          key: packages/aws-lambda-otel-extension/opt/otel-extension/node-modules-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('packages/aws-lambda-otel-extension/opt/otel-extension/package.json') }}
          restore-keys: |
            packages/aws-lambda-otel-extension/opt/otel-extension/node-modules-v16-${{ runner.os }}-${{ github.ref }}-
            packages/aws-lambda-otel-extension/opt/otel-extension/node-modules-v16-${{ runner.os }}-refs/heads/main-
      - name: Retrieve packages/aws-lambda-otel-extension-dist/node_modules from cache
        id: cacheAwsLambdaOtelExtensionDistNodeModules
        uses: actions/cache@v2
        with:
          path: packages/aws-lambda-otel-extension-dist/node_modules
          key: packages/aws-lambda-otel-extension-dist/node-modules-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('packages/aws-lambda-otel-extension-dist/package.json') }}
          restore-keys: |
            packages/aws-lambda-otel-extension-dist/node-modules-v16-${{ runner.os }}-${{ github.ref }}-
            packages/aws-lambda-otel-extension-dist/node-modules-v16-${{ runner.os }}-refs/heads/main-
      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install main project dependencies
        if: steps.cacheNodeModules.outputs.cache-hit != 'true'
        run: |
          npm update --save-dev --no-save
      - name: Install packages/aws-lambda-otel-extension dependencies
        if: steps.cacheAwsLambdaOtelExtensionNodeModules.outputs.cache-hit != 'true'
        run: |
          cd packages/aws-lambda-otel-extension
          npm update --no-save
          npm update --save-dev --no-save
      - name: Install packages/aws-lambda-otel-extension/opt/otel-extension dependencies
        if: steps.cacheAwsLambdaOtelExtensionOptOtelExtensionNodeModules.outputs.cache-hit != 'true'
        run: |
          cd packages/aws-lambda-otel-extension/opt/otel-extension
          npm update --no-save
      - name: Install packages/aws-lambda-otel-extension-dist dependencies
        if: steps.cacheAwsLambdaOtelExtensionDistNodeModules.outputs.cache-hit != 'true'
        run: |
          cd packages/aws-lambda-otel-extension-dist
          npm update --save-dev --no-save

      - name: Validate Prettier formatting
        run: npm run prettier-check:updated
      - name: Validate ESLint rules
        run: npm run lint:updated
      - name: Unit tests
        run: |
          cd packages/aws-lambda-otel-extension
          npm test

  linuxNode14:
    name: '[Linux] Node.js v14: Isolated unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve ~/.npm from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-v14-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**package*.json') }}
          restore-keys: |
            npm-v14-${{ runner.os }}-${{ github.ref }}-
            npm-v14-${{ runner.os }}-refs/heads/main-

      - name: Retrieve node_modules from cache
        id: cacheNodeModules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-v14-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('package.json') }}
          restore-keys: |
            node-modules-v14-${{ runner.os }}-${{ github.ref }}-
            node-modules-v14-${{ runner.os }}-refs/heads/main-
      - name: Retrieve packages/aws-lambda-otel-extension/node_modules from cache
        id: cacheAwsLambdaOtelExtensionNodeModules
        uses: actions/cache@v2
        with:
          path: packages/aws-lambda-otel-extension/node_modules
          key: packages/aws-lambda-otel-extension/node-modules-v14-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('packages/aws-lambda-otel-extension/package.json') }}
          restore-keys: |
            packages/aws-lambda-otel-extension/node-modules-v14-${{ runner.os }}-${{ github.ref }}-
            packages/aws-lambda-otel-extension/node-modules-v14-${{ runner.os }}-refs/heads/main-
      - name: Retrieve packages/aws-lambda-otel-extension/opt/otel-extension/node_modules from cache
        id: cacheAwsLambdaOtelExtensionOptOtelExtensionNodeModules
        uses: actions/cache@v2
        with:
          path: packages/aws-lambda-otel-extension/opt/otel-extension/node_modules
          key: packages/aws-lambda-otel-extension/opt/otel-extension/node-modules-v14-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('packages/aws-lambda-otel-extension/opt/otel-extension/package.json') }}
          restore-keys: |
            packages/aws-lambda-otel-extension/opt/otel-extension/node-modules-v14-${{ runner.os }}-${{ github.ref }}-
            packages/aws-lambda-otel-extension/opt/otel-extension/node-modules-v14-${{ runner.os }}-refs/heads/main-

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install main project dependencies
        if: steps.cacheNodeModules.outputs.cache-hit != 'true'
        run: |
          npm update --save-dev --no-save
      - name: Install packages/aws-lambda-otel-extension dependencies
        if: steps.cacheAwsLambdaOtelExtensionNodeModules.outputs.cache-hit != 'true'
        run: |
          cd packages/aws-lambda-otel-extension
          npm update --no-save
          npm update --save-dev --no-save
      - name: Install packages/aws-lambda-otel-extension/opt/otel-extension dependencies
        if: steps.cacheAwsLambdaOtelExtensionOptOtelExtensionNodeModules.outputs.cache-hit != 'true'
        run: |
          cd packages/aws-lambda-otel-extension/opt/otel-extension
          npm update --no-save

      - name: Unit tests
        run: |
          # npm v6 doesn't add parent node_modules/.bin to PATH, workaround it
          export PATH="$PWD/node_modules/.bin:$PATH"
          cd packages/aws-lambda-otel-extension
          npm run test:isolated
